spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/apiInfoDB.db
    username:
    password:
  jpa:
    database-platform: com.apijava.apijava.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true